version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d:ro
      - nginx-configs:/etc/nginx/conf.d
      - nginx-contents:/usr/share/nginx/html
      - nginx-logs:/var/log/nginx

  nginx-gen:
    build:
      context: .
      dockerfile: ./docker/nginx-gen/Dockerfile
    command: -notify reload-nginx.sh -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-configs:/etc/nginx/conf.d

volumes:
  nginx-configs: {}
  nginx-contents: {}
  nginx-logs: {}
