version: '2'

services:
  nginx:
    image: nginx:1.11-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d:ro
      - /etc/nginx/conf.d
      - /usr/share/nginx/html
      - nginx-logs:/var/log/nginx

  nginx-gen:
    command: -notify-sighup $NGINX_CONTAINER -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    entrypoint: docker-entrypoint.sh
    image: jwilder/docker-gen
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:ro
      - ./nginx-proxy/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - ./vhost.d:/etc/nginx/vhost.d:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    volumes_from:
      - nginx

  nginx-letsencrypt:
    environment:
      - NGINX_DOCKER_GEN_CONTAINER
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx

volumes:
  nginx-logs: {}
