version: '3.2'

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./htpasswd:/etc/nginx/htpasswd:ro
      - ./vhost.d:/etc/nginx/vhost.d:ro
      - nginx-conf:/etc/nginx/conf.d
      - nginx-contents:/usr/share/nginx/html
      - nginx-logs:/var/log/nginx

  nginx-gen:
    build:
      context: .
      dockerfile: ./docker/nginx-gen/Dockerfile
    command: -notify reload-nginx.sh -notify-output -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./htpasswd:/etc/nginx/htpasswd:ro
      - ./vhost.d:/etc/nginx/vhost.d:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-conf:/etc/nginx/conf.d:nocopy

volumes:
  nginx-conf: {}
  nginx-contents: {}
  nginx-logs: {}
